canvas:
  width: 512
  height: 512

world:
  camera:
    fov: 45
    pos:
      x: 0.0
      y: 0.0
      z: -5.0
    lookingAt:
      x: 0.0
      y: 0.0
      z: 0.0

  lights:

    - x: -5.5
      y: 5.0
      z: 1.5
      color:
        r: 0.07
        g: 0.49
        b: 0.07
    - x: 0.5
      y: 5.0
      z: 0.0
      color:
        r: 0.07
        g: 0.07
        b: 0.49
    - x: -1.8
      y: 3.0
      z: -2.0
      color:
        r: 0.21
        g: 0.21
        b: 0.35
    - x: 5.5
      y: 5.0
      z: 1.5
      color:
        r: 0.49
        g: 0.07
        b: 0.07

  spheres:
    - center:
        x: 0.0
        y: 0.0
        z: 0.0
      radius: 1.0
      specularColor:
        r: 0.5
        g: 0.5
        b: 0.5
      specularConstant: 0.7
      diffuseColor:
        r: 1.0
        g: 1.0
        b: 1.0
      diffuseConstant: 0.7
      ambientColor:
        r: 1.0
        g: 1.0
        b: 1.0
      ambientConstant: 0.06
      shininess: 100

    - center:
        x: 0.65
        y: -0.5
        z: -1.5
      radius: 0.3
      specularColor:
        r: 0.5
        g: 0.5
        b: 0.5
      specularConstant: 0.7
      diffuseColor:
        r: 1.0
        g: 1.0
        b: 1.0
      diffuseConstant: 0.7
      ambientColor:
        r: 1.0
        g: 1.0
        b: 1.0
      ambientConstant: 0.06
      shininess: 100
